server:
  port: 7070
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource: 
    autoReconnect: true
    driver-class-name: com.mysql.jdbc.Driver
    password: ${QUIZ_CONNECTION_PASSWORD}
    testOnBorrow: true
    url: ${QUIZ_CONNECTION_STRING}
    username: ${QUIZ_CONNECTION_USER}
    validationQuery: "SELECT 1"
  jpa: 
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
data:
  file: ${QUIZ_DATA_FOLDER}
  result_output: ${QUIZ_RESULT_FOLDER}
  font_file: ${QUIZ_FONT_FILE}
