server:
  port: ${QUIZ_PORT}
logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    com.auth0.example: TRACE
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${QUIZ_AUTH_ISSUER_URI}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      database: ${QUIZ_CONNECTION_DATABASE}
      uri: ${QUIZ_CONNECTION_STRING}
  thymeleaf:
    cache: false
data:
  ddl_auto: ${QUIZ_DDL_AUTO}
  file: ${QUIZ_DATA_FOLDER}
  result_output: ${QUIZ_RESULT_FOLDER}
  font_file: ${QUIZ_FONT_FILE}
  google:
    app_name: ${QUIZ_GOOGLE_APP_NAME}
    tokens_dir: ${QUIZ_GOOGLE_TOKENS_DIR}
    credentials_json: ${QUIZ_GOOGLE_CREDENTIALS_JSON}
    spreadsheet_id: ${QUIZ_GOOGLE_SPREADSHEET_ID}
auth0:
  audience: ${QUIZ_AUTH_AUDIENCE}
